CREATE DATABASE IF NOT EXISTS thuc_tap; 
USE thuc_tap;

CREATE TABLE IF NOT EXISTS khoa
(
	khoa_ID 		CHAR(10) NOT NULL PRIMARY KEY,
    Tenkhoa 		CHAR(30) NOT NULL,
    Dienthoai 		CHAR(10) NULL UNIQUE KEY
);

CREATE TABLE GiangVien
(
	ID_Gv 		INT NOT NULL PRIMARY KEY,
    name_Gv		CHAR(30) NOT NULL,
    Luong		DECIMAL(5,2) NOT NULL,
	Khoa_ID		CHAR(10) NOT NULL,
FOREIGN KEY ( Khoa_ID ) REFERENCES Khoa ( Khoa_ID ) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS SinhVien
(
	ID_Sv		INT NOT NULL PRIMARY KEY,
    Name_Sv		CHAR(30) NOT NULL,
    Khoa_ID		CHAR(10) NOT NULL,
    NamSinh		TINYINT(4) NULL,
    QueQuan		CHAR(30) NULL,
FOREIGN KEY ( Khoa_ID ) REFERENCES Khoa ( Khoa_ID ) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS DeTai
(
	DeTai_ID		CHAR(10) NOT NULL PRIMARY KEY,
    Name_Dt			CHAR(30) NOT NULL,
    KinhPhi			INT NULL,
    NoiThucTap		CHAR(30)
);

CREATE TABLE IF NOT EXISTS HuongDan
(
	ID_Sv		INT NOT NULL PRIMARY KEY,
    DeTai_ID	CHAR(10) NOT NULL,
    ID_Gv		INT NOT NULL,
    KetQua		DECIMAL(5,2),
FOREIGN KEY ( DeTai_ID ) REFERENCES DeTai ( DeTai_ID ) ON DELETE CASCADE,
FOREIGN KEY ( ID_Gv ) REFERENCES GiangVien ( ID_Gv ) ON DELETE CASCADE
);

