# This is a basic workflow to help you get started with Actions

name: Send message

# Controls when the action will run. 
on:
  workflow_dispatch:
  schedule:
  - cron: "0 23 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.16.1
      - run: npm ci
      - name: Send message
        run: npm run send
